Refactor-interface DB
Tools4everBV/HelloID-Conn-Prov-Target-SaltoSpace pull request #1
Opened 2023-10-04 14:50 UTC by ChielB

I removed the need of the SA task by directly editing the interface table. Removed the HelloID tables from the config and create,update, delete and set permissions.

2023-10-30 13:54 UTC, Rick-Jongbloed commented on config.json
config file looks good

2023-10-30 13:58 UTC, Rick-Jongbloed requested changes

2023-10-30 13:58 UTC, Rick-Jongbloed commented on config.json
Config file looks good

2023-10-30 13:58 UTC, Rick-Jongbloed commented on create.ps1
> +    #$queryAccountLookupSaltoSpace = "SELECT ExtID FROM [$sqlDatabaseSaltoSpace].[dbo].[tb_Users] INNER JOIN [$sqlDatabaseSaltoSpace].[dbo].[tb_Users_Ext] ON tb_Users.id_user = tb_Users_Ext.id_user W
remote comment

2023-10-30 13:58 UTC, Rick-Jongbloed commented on create.ps1
> +    <#
remove comment

2023-10-30 13:58 UTC, Rick-Jongbloed commented on permissionSetAccessGroups.ps1
> +$dryRun =$false
should not be in here

2023-10-30 13:58 UTC, Rick-Jongbloed commented on permissionSetAccessGroups.ps1
> +$queryCheckPermission = "SELECT [ExtZoneIDList] FROM $sqlDatabaseHelloIdAccountTable WHERE $($config.correlationAccountFieldSaltoStaging)=$aRef and  [ExtZoneIDList] like '%$($pRef.reference)%'"
Lets discuss if this is the best way to do this

2023-10-30 13:58 UTC, Rick-Jongbloed commented on config.json
I miss an update on the readme file

2023-10-30 13:58 UTC, Rick-Jongbloed commented on config.json
Also don't forget to update the intake document

2024-02-28 20:42 UTC, rschouten97 commented
@ChielB  please see the comment of Rick-Jongbloed.
Please plan time for this or request this by the Github team so we can plan this.

2024-06-24 11:43 UTC, Rick-Jongbloed commented
After checking this again, there are some changes to be made:
1. Please make sure correlation works, as the current script won't work when there are already users.
2. Please remove all references to the 'HelloID' table from each script and the configuration
3. Please make sure the table we interface with is called the staging table

2024-10-17 20:21 UTC, closed without merging