New powershell connector
Tools4everBV/HelloID-Conn-Prov-Target-SaltoSpace pull request #2
Opened 2024-10-17 21:11 UTC by rschouten97

2024-11-08 14:52 UTC, Rick-Jongbloed requested changes
Ziet er goed uit. Er zijn nog wel een paar dingetjes je nog even op kan pakken:

1. Flatten functie is volgens mij overbodig in script waar de functie nu nog gebruikt wordt. Ik heb de functie erin geplaatst omdat er punten in de fieldnamen zaten.
2. Flatten functie in permissiescripts worden niet gebruikt
3. Ik mis het SQL bestand om de tabel mee aan te maken
4. Denk even na of je een punt aan het einde van een zin in de audit logging wil hebben.
5. Custom veld in mapping en correlation code
6. Geen beschrijving van bestanden in assets mapje
7. Andere puntjes die ik vergeten ben te melden. Zie comments :-)

2024-11-08 14:52 UTC, Rick-Jongbloed commented on permissions/AccessGroups/revokePermission.ps1
> +function ConvertTo-FlatObject {
i don't think we use this function in this script

2024-11-08 14:52 UTC, Rick-Jongbloed commented on permissions/AccessGroups/permissions.ps1
> +function ConvertTo-FlatObject {
i don't think we use this function in this script

2024-11-08 14:52 UTC, Rick-Jongbloed commented on permissions/AccessGroups/grantPermissions.ps1
> +function ConvertTo-FlatObject {
i don't think we use this function in this script

2024-11-08 14:52 UTC, Rick-Jongbloed commented on create.ps1
> +function ConvertTo-FlatObject {
Do we still need this function now the fields with dots in it are gone in the field mapping?

2024-11-08 14:52 UTC, Rick-Jongbloed commented on delete.ps1
> +function ConvertTo-FlatObject {
Do we still need this function now the fields with dots in it are gone in the field mapping?

2024-11-08 14:52 UTC, Rick-Jongbloed commented on update.ps1
> +function ConvertTo-FlatObject {
Do we still need this function now the fields with dots in it are gone in the field mapping?

2024-11-08 14:52 UTC, Rick-Jongbloed commented on create.ps1
> +            Write-Warning "Correlation is disabled."
moet dit geen throw zijn?

2024-11-08 14:52 UTC, Rick-Jongbloed commented on create.ps1
> +    if ($actionContext.Configuration.correlateOnly -eq $true -and ($getSaltoAccountResponse | Measure-Object).count -eq 0) {
Als correlation = $false dan loopt ie door denk ik?

2025-01-31 13:14 UTC, Rick-Jongbloed commented
@rschouten97 Kijk hier ook even naar: https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-SaltoSpace/issues/3

2025-02-03 12:37 UTC, rschouten97 commented on create.ps1
> +function ConvertTo-FlatObject {
No longer needed as there are no fields with a . in the mapping

2025-02-03 12:39 UTC, rschouten97 commented on delete.ps1
> +function ConvertTo-FlatObject {
It might not be needed for the fieldmapping, but it's also used in the response.
As I can't judge directly whether this is needed, but it doesn't provide errors or issues, I left this in as we are sure it works with this function.

2025-02-03 12:39 UTC, rschouten97 commented on update.ps1
> +function ConvertTo-FlatObject {
It might not be needed for the fieldmapping, but it's also used in the response.
As I can't judge directly whether this is needed, but it doesn't provide errors or issues, I left this in as we are sure it works with this function.

2025-02-03 12:39 UTC, rschouten97 commented on permissions/AccessGroups/grantPermissions.ps1
> +function ConvertTo-FlatObject {
Not used indeed, removed function.

2025-02-03 12:48 UTC, rschouten97 commented on README.md
> +   - **Create the Staging Table**: Use the provided SQL script (`createStagingDB.sql`) to create the necessary table in the staging database.
Added.

2025-02-03 12:49 UTC, rschouten97 commented on README.md
> +| `permissions.ps1`      | Retrieve all groups and provide them as entitlements |                                                |
Done.

2025-02-03 12:56 UTC, rschouten97 commented on assets/reports.sql
Done.

2025-02-03 12:59 UTC, rschouten97 commented on README.md
> +    | **Account Correlation Field** | `Dummy2`     |
Currently both projects I implemented this at we used Dummy2, if this changes in the future we can always change it.
However I did add a remark that dummy2 is just an example and this should be configured properyl for each project.

2025-02-03 13:13 UTC, rschouten97 commented on assets/correlationReport.ps1
> +$personCorrelationField = "Custom.Actuele06" # e.g., "externalId"
changed.

2025-02-03 13:13 UTC, rschouten97 commented on assets/correlationReport.ps1
> +#################################################
added.

2025-02-03 13:14 UTC, rschouten97 commented on create.ps1
> +            Write-Warning "Correlation is disabled."
No, but the one above should have been, changed.

2025-02-03 13:15 UTC, rschouten97 commented on fieldMapping.json
> +                    "Value": "\"Person.Custom.Actuele06\"",
changed to default person field.

2025-02-03 13:16 UTC, merged